 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfr4e9rQvth07259CZ1UQm-bHfnufGN54',
    appId: '1:39062065402:web:d131f4b7e942f75a617943',
    messagingSenderId: '39062065402',
    projectId: 'zadmarket-8ae33',
    authDomain: 'zadmarket-8ae33.firebaseapp.com',
    storageBucket: 'zadmarket-8ae33.firebasestorage.app',
    measurementId: 'G-BV8GZHVJXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmolL3FrGhE1nXOQe5ELiyrNl8Yf1gPWU',
    appId: '1:39062065402:android:5d29ca516b1fca8d617943',
    messagingSenderId: '39062065402',
    projectId: 'zadmarket-8ae33',
    storageBucket: 'zadmarket-8ae33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlNLOJ6Fn6DG7sspud21nXhuF_m39pSw',
    appId: '1:39062065402:ios:cd22c94c626576e9617943',
    messagingSenderId: '39062065402',
    projectId: 'zadmarket-8ae33',
    storageBucket: 'zadmarket-8ae33.firebasestorage.app',
    androidClientId: '39062065402-24tm3v5kuh9dd5qbi51fpci3e5prineg.apps.googleusercontent.com',
    iosClientId: '39062065402-6qoh5dpldcec636ld9g0ultqe3u2di3r.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.stackfoodUserAppDevMehedi',
  );

}